# Generated by Django 5.1.2 on 2024-11-06 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_escola_profile_escola'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='escola',
        ),
        migrations.DeleteModel(
            name='Escola',
        ),
    ]
