# Generated by Django 5.0 on 2024-09-28 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_categoria_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentoestoque',
            name='destino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fornecedor'),
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10),
        ),
    ]
