# Generated by Django 5.0 on 2024-09-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_movimentoestoque_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentoestoque',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
