# Generated by Django 5.0 on 2024-10-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo',
            field=models.CharField(choices=[('diretor', 'Diretor'), ('nutricionista', 'Nutricionista'), ('adm', 'Administrador')], default='adm', max_length=20),
        ),
    ]
