# Generated by Django 5.1.3 on 2024-11-07 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_escola'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.escola'),
        ),
    ]
