# Generated by Django 5.0 on 2024-09-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_movimentoestoque_data_movimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentoestoque',
            name='data_movimento',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('edicao', 'Edição')], max_length=10),
        ),
    ]
