# Generated by Django 5.0 on 2024-11-09 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_categoria_escola'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='administrador',
        ),
    ]
