# Generated by Django 5.0 on 2024-09-28 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_movimentoestoque_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentoestoque',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fornecedor'),
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='nota_fiscal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='tipo',
            field=models.CharField(choices=[('adição', 'Adição'), ('edição', 'Edição'), ('exclusão', 'Exclusão')], max_length=10),
        ),
    ]
