# Generated by Django 5.0 on 2024-09-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_movimentoestoque_fornecedor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentoestoque',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='movimentoestoque',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='movimentoestoque',
            name='nota_fiscal',
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='tipo',
            field=models.CharField(choices=[('adicao', 'Adição'), ('edicao', 'Edição'), ('exclusao', 'Exclusão')], max_length=10),
        ),
    ]
