# Generated by Django 5.0 on 2024-09-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_movimentoestoque_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
